# Generated by Django 5.2 on 2025-04-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nicepostapp', '0005_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
