# Generated by Django 5.2 on 2025-05-01 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicepostapp', '0006_rename_user_comments_author_rename_user_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgs',
            name='imgs',
        ),
        migrations.CreateModel(
            name='ImgOrVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='post_files/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_files', to='nicepostapp.post')),
            ],
        ),
        migrations.DeleteModel(
            name='GIF',
        ),
        migrations.DeleteModel(
            name='Imgs',
        ),
    ]
