# Generated by Django 5.2 on 2025-05-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicepostapp', '0007_remove_imgs_imgs_imgorvideo_delete_gif_delete_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgorvideo',
            name='files',
            field=models.FileField(blank=True, upload_to='post_files/'),
        ),
    ]
