# Generated by Django 5.2 on 2025-04-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicepost_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostModel',
            new_name='Post',
        ),
        migrations.AlterField(
            model_name='imgs',
            name='post_imgs',
            field=models.ImageField(blank=True, upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='post_video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
